version: '3.7'

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  plex-assistant:
    depends_on:
      - mongodb_container
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: plex-assistant
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
  react-app:
    depends_on:
      - plex-assistant
    build:
      context: ./react-app
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./react-app:/app
    container_name: react-app
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run vite:start
volumes:
  mongodb_data_container: